// import { Claim } from './claim';

// export const CLAIMS: Claim[] = [
// 	{
// 		id: 1,
// 		name: 'Wifi Problem',
// 		flag: 'f/f3/Flag_of_Russia.svg',
// 		area: "Pending",
// 		population: new Date("2019-01-12"),
// 	},
// 	{
// 		id: 2,
// 		name: 'Roommate Problem',
// 		flag: 'c/c3/Flag_of_France.svg',
// 		area: "Done",
// 		population: new Date("2019-01-14"),
// 	},
// 	{
// 		id: 3,
// 		name: 'Moisture Problem',
// 		flag: 'b/ba/Flag_of_Germany.svg',
// 		area: "Cancelled",
// 		population: new Date("2019-01-17"),
// 	},
// 	{
// 		id: 4,
// 		name: 'Stuff Lack',
// 		flag: '5/5c/Flag_of_Portugal.svg',
// 		area: "Done",
// 		population: new Date("2019-01-12"),
// 	},
// 	{
// 		id: 5,
// 		name: 'Door Problem',
// 		flag: 'c/cf/Flag_of_Canada.svg',
// 		area: "Cancelled",
// 		population: new Date("2019-01-13"),
// 	},
// 	{
// 		id: 6,
// 		name: 'Water Problem',
// 		flag: '2/21/Flag_of_Vietnam.svg',
// 		area: "Pending",
// 		population: new Date("2019-01-10"),
// 	},
// 	{
// 		id: 7,
// 		name: 'Electricity Problem',
// 		flag: '0/05/Flag_of_Brazil.svg',
// 		area: "Cancelled",
// 		population: new Date("2019-02-16"),
// 	},
// 	{
// 		id: 8,
// 		name: 'Cleanliness Problem',
// 		flag: 'f/fc/Flag_of_Mexico.svg',
// 		area: "Cancelled",
// 		population: new Date("2019-03-16"),
// 	},
// 	{
// 		id: 9,
// 		name: 'Electricity Problem',
// 		flag: 'a/a4/Flag_of_the_United_States.svg',
// 		area: "Done",
// 		population: new Date("2019-01-24"),
// 	},
// 	{
// 		id: 10,
// 		name: 'Window Problem',
// 		flag: '4/41/Flag_of_India.svg',
// 		area: "Done",
// 		population: new Date("2019-04-16"),
// 	},
// 	{
// 		id: 11,
// 		name: 'Cleanliness Problem',
// 		flag: '9/9f/Flag_of_Indonesia.svg',
// 		area: "Pending",
// 		population: new Date("2019-03-06"),
// 	},
// 	{
// 		id: 12,
// 		name: 'Door Problem',
// 		flag: '3/38/Flag_of_Tuvalu.svg',
// 		area: "Done",
// 		population: new Date("2019-02-16"),
// 	},
// 	{
// 		id: 13,
// 		name: 'Wifi Problem ',
// 		flag: 'f/fa/Flag_of_the_People%27s_Republic_of_China.svg',
// 		area: "Done",
// 		population: new Date("2019-01-26"),
// 	},
// ];